/**
 * Guardian to Provider Migration
 * 
 * This migration converts existing guardian users and their associated
 * students/classes to use the provider system.
 * 
 * Steps:
 * 1. Find all guardian users
 * 2. Create provider entity for each guardian
 * 3. Update students: guardianId to providerId
 * 4. Update classes: isGuardianLinked to providerId
 * 5. Deprecate guardian user role
 * 
 * IMPORTANT: Run this AFTER deploying schema changes
 * BACKUP DATABASE BEFORE RUNNING
 * 
 * @see GUARDIAN_TO_PROVIDER_MIGRATION_PLAN.md
 */

import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import type { Id } from "./_generated/dataModel";

/**
 * Query to check current guardian data before migration
 */
export const previewMigration = query({
  args: {},
  handler: async (ctx) => {
    // Count guardian users
    const allUsers = await ctx.db.query("users").collect();
    const guardianUsers = allUsers.filter(u => u.role === "guardian");

    // Count students linked to guardians
    const allStudents = await ctx.db.query("students").collect();
    const guardianStudents = allStudents.filter(s => s.guardianId !== undefined);

    // Count guardian-linked classes
    const allClasses = await ctx.db.query("classes").collect();
    const guardianClasses = allClasses.filter(c => c.isGuardianLinked === true);

    return {
      guardianUsers: guardianUsers.length,
      guardianUsersDetails: guardianUsers.map(u => ({
        id: u._id,
        username: u.username,
      })),
      guardianStudents: guardianStudents.length,
      guardianClasses: guardianClasses.length,
      summary: `Found ${guardianUsers.length} guardian users, ${guardianStudents.length} students, ${guardianClasses.length} classes to migrate`,
    };
  },
});

/**
 * Main migration mutation
 * 
 * @param adminId - ID of admin user running the migration
 * @param dryRun - If true, preview without making changes
 * @returns Migration log with details of all changes
 */
export const migrateGuardiansToProviders = mutation({
  args: { 
    adminId: v.id("users"),
    dryRun: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    // 1. Verify admin authorization
    const admin = await ctx.db.get(args.adminId);
    if (!admin || admin.role !== "admin") {
      throw new Error("Unauthorized: Only admins can run migrations");
    }

    console.log("Admin verified:", admin.username);

    // 2. Find all guardian users
    const allUsers = await ctx.db.query("users").collect();
    const guardians = allUsers.filter(u => u.role === "guardian");

    if (guardians.length === 0) {
      return {
        success: true,
        message: "No guardian users found - migration not needed",
        guardiansProcessed: 0,
        migrationLog: [],
      };
    }

    console.log(`Found ${guardians.length} guardian users to migrate`);

    const migrationLog = [];
    const errors = [];

    // 3. Process each guardian
    for (const guardian of guardians) {
      try {
        console.log(`Processing guardian: ${guardian.username} (${guardian._id})`);

        // Create provider entity
        let providerId: Id<"providers"> | string;
        if (!args.dryRun) {
          providerId = await ctx.db.insert("providers", {
            name: `Guardian - ${guardian.username}`,
            nameTh: `ผู้ปกครอง - ${guardian.username}`,
            category: "guardian",
            createdBy: args.adminId,
            isActive: true,
            createdAt: Date.now(),
            isAutoGenerated: false, // Migrated from existing guardian user
          });
          console.log(`  Created provider: ${providerId}`);
        } else {
          providerId = "DRY_RUN_PROVIDER_ID";
          console.log(`  [DRY RUN] Would create provider for ${guardian.username}`);
        }

        // Find students linked to this guardian
        const students = await ctx.db
          .query("students")
          .withIndex("by_guardian_id", q => q.eq("guardianId", guardian._id))
          .collect();

        console.log(`  Found ${students.length} students to update`);

        // Update each student
        let studentsUpdated = 0;
        for (const student of students) {
          if (!args.dryRun && typeof providerId !== 'string') {
            await ctx.db.patch(student._id, {
              providerId,
              // Keep guardianId for now (rollback safety)
            });
          }
          studentsUpdated++;
        }

        if (!args.dryRun) {
          console.log(`  Updated ${studentsUpdated} students`);
        } else {
          console.log(`  [DRY RUN] Would update ${studentsUpdated} students`);
        }

        // Find and update classes for these students
        let classesUpdated = 0;
        for (const student of students) {
          const classes = await ctx.db
            .query("classes")
            .withIndex("by_student", q => q.eq("studentId", student._id))
            .collect();

          const guardianClasses = classes.filter(c => c.isGuardianLinked === true);

          for (const classItem of guardianClasses) {
            if (!args.dryRun && typeof providerId !== 'string') {
              await ctx.db.patch(classItem._id, {
                providerId,
                // Keep isGuardianLinked for now (rollback safety)
              });
            }
            classesUpdated++;
          }
        }

        if (!args.dryRun) {
          console.log(`  Updated ${classesUpdated} classes`);
        } else {
          console.log(`  [DRY RUN] Would update ${classesUpdated} classes`);
        }

        migrationLog.push({
          guardianId: guardian._id,
          guardianUsername: guardian.username,
          providerId: args.dryRun ? "DRY_RUN" : providerId,
          studentsUpdated,
          classesUpdated,
          status: "success",
        });

      } catch (err) {
        const error = err as Error;
        console.error(`  Error processing guardian ${guardian.username}:`, error);
        errors.push({
          guardianId: guardian._id,
          guardianUsername: guardian.username,
          error: error.message,
        });
        migrationLog.push({
          guardianId: guardian._id,
          guardianUsername: guardian.username,
          providerId: null,
          studentsUpdated: 0,
          classesUpdated: 0,
          status: "failed",
          error: error.message,
        });
      }
    }

    // Summary
    const summary = {
      success: errors.length === 0,
      dryRun: args.dryRun || false,
      guardiansProcessed: guardians.length,
      successfulMigrations: migrationLog.filter(m => m.status === "success").length,
      failedMigrations: errors.length,
      migrationLog,
      errors: errors.length > 0 ? errors : undefined,
    };

    if (args.dryRun) {
      console.log("DRY RUN COMPLETE - No changes made");
    } else {
      console.log("MIGRATION COMPLETE");
    }
    console.log(JSON.stringify(summary, null, 2));

    return summary;
  },
});

/**
 * Rollback migration (if needed)
 * Reverses the provider migration by clearing providerId fields
 * 
 * Only use if migration fails or needs to be undone
 */
export const rollbackMigration = mutation({
  args: { 
    adminId: v.id("users"),
    confirm: v.boolean(), // Must be true to execute
  },
  handler: async (ctx, args) => {
    if (!args.confirm) {
      throw new Error("Rollback not confirmed - set confirm: true to proceed");
    }

    // Verify admin
    const admin = await ctx.db.get(args.adminId);
    if (!admin || admin.role !== "admin") {
      throw new Error("Unauthorized: Only admins can run rollback");
    }

    console.log("ROLLING BACK MIGRATION...");

    // Clear providerId from all students that have guardianId
    const students = await ctx.db.query("students").collect();
    const studentsWithBoth = students.filter(s => s.guardianId && s.providerId);

    for (const student of studentsWithBoth) {
      await ctx.db.patch(student._id, {
        providerId: undefined,
      });
    }

    // Clear providerId from all classes that have isGuardianLinked
    const classes = await ctx.db.query("classes").collect();
    const classesWithBoth = classes.filter(c => c.isGuardianLinked && c.providerId);

    for (const classItem of classesWithBoth) {
      await ctx.db.patch(classItem._id, {
        providerId: undefined,
      });
    }

    console.log("ROLLBACK COMPLETE");

    return {
      success: true,
      studentsRolledBack: studentsWithBoth.length,
      classesRolledBack: classesWithBoth.length,
    };
  },
});
