/**
 * Guardian to Provider Migration
 * 
 * This migration converts existing guardian users and their associated
 * students/classes to use the provider system.
 * 
 * Steps:
 * 1. Find all guardian users and create provider entities
 * 2. Update students: guardianId to providerId
 * 3. Find students without schoolId/providerId and create pseudo-provider
 * 4. Update classes: isGuardianLinked to providerId
 * 5. Clean up deprecated fields (separate function)
 * 
 * IMPORTANT: Run this AFTER deploying schema changes
 * BACKUP DATABASE BEFORE RUNNING
 * 
 * @see docs/migrations/GUARDIAN_TO_PROVIDER_MIGRATION_PLAN.md
 */

import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import type { Id } from "./_generated/dataModel";

/**
 * Query to check current guardian data before migration
 */
export const previewMigration = query({
  args: {},
  handler: async (ctx) => {
    // Count guardian users
    const allUsers = await ctx.db.query("users").collect();
    const guardianUsers = allUsers.filter(u => u.role === "guardian");

    // Count students linked to guardians
    const allStudents = await ctx.db.query("students").collect();
    const guardianStudents = allStudents.filter(s => s.guardianId !== undefined);
    
    // Count students without any link (need pseudo-provider)
    const orphanStudents = allStudents.filter(s => 
      !s.schoolId && !s.providerId && !s.guardianId
    );

    // Count guardian-linked classes
    const allClasses = await ctx.db.query("classes").collect();
    const guardianClasses = allClasses.filter(c => c.isGuardianLinked === true);
    
    // Count classes without providerId but with isGuardianLinked
    const classesNeedingProvider = allClasses.filter(c => 
      c.isGuardianLinked === true && !c.providerId
    );

    return {
      guardianUsers: guardianUsers.length,
      guardianUsersDetails: guardianUsers.map(u => ({
        id: u._id,
        username: u.username,
      })),
      guardianStudents: guardianStudents.length,
      orphanStudents: orphanStudents.length,
      orphanStudentsDetails: orphanStudents.slice(0, 5).map(s => ({
        id: s._id,
        name: `${s.firstName} ${s.lastName}`,
        grade: s.grade,
      })),
      guardianClasses: guardianClasses.length,
      classesNeedingProvider: classesNeedingProvider.length,
      summary: `Found ${guardianUsers.length} guardian users, ${guardianStudents.length} students with guardianId, ${orphanStudents.length} orphan students needing pseudo-provider, ${guardianClasses.length} guardian-linked classes (${classesNeedingProvider.length} need providerId)`,
    };
  },
});

/**
 * Main migration mutation
 * 
 * @param adminId - ID of admin user running the migration
 * @param dryRun - If true, preview without making changes
 * @returns Migration log with details of all changes
 */
export const migrateGuardiansToProviders = mutation({
  args: { 
    adminId: v.id("users"),
    dryRun: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    // 1. Verify admin authorization
    const admin = await ctx.db.get(args.adminId);
    if (!admin || admin.role !== "admin") {
      throw new Error("Unauthorized: Only admins can run migrations");
    }

    console.log("Admin verified:", admin.username);

    const migrationLog = [];
    const errors = [];
    let pseudoProviderCreated = false;
    let pseudoProviderId: Id<"providers"> | string = "DRY_RUN_PSEUDO_PROVIDER";

    // 2. Find all guardian users
    const allUsers = await ctx.db.query("users").collect();
    const guardians = allUsers.filter(u => u.role === "guardian");

    console.log(`Found ${guardians.length} guardian users to migrate`);

    // 3. Process each guardian
    for (const guardian of guardians) {
      try {
        console.log(`Processing guardian: ${guardian.username} (${guardian._id})`);

        // Create provider entity
        let providerId: Id<"providers"> | string;
        if (!args.dryRun) {
          providerId = await ctx.db.insert("providers", {
            name: `Guardian - ${guardian.username}`,
            nameTh: `ผู้ปกครอง - ${guardian.username}`,
            category: "guardian",
            createdBy: args.adminId,
            isActive: true,
            createdAt: Date.now(),
            isAutoGenerated: false, // Migrated from existing guardian user
          });
          console.log(`  Created provider: ${providerId}`);
        } else {
          providerId = "DRY_RUN_PROVIDER_ID";
          console.log(`  [DRY RUN] Would create provider for ${guardian.username}`);
        }

        // Find students linked to this guardian
        const students = await ctx.db
          .query("students")
          .withIndex("by_guardian_id", q => q.eq("guardianId", guardian._id))
          .collect();

        console.log(`  Found ${students.length} students to update`);

        // Update each student
        let studentsUpdated = 0;
        for (const student of students) {
          if (!args.dryRun && typeof providerId !== 'string') {
            await ctx.db.patch(student._id, {
              providerId,
              // Keep guardianId for now (rollback safety)
            });
          }
          studentsUpdated++;
        }

        if (!args.dryRun) {
          console.log(`  Updated ${studentsUpdated} students`);
        } else {
          console.log(`  [DRY RUN] Would update ${studentsUpdated} students`);
        }

        // Find and update classes for these students
        let classesUpdated = 0;
        for (const student of students) {
          const classes = await ctx.db
            .query("classes")
            .withIndex("by_student", q => q.eq("studentId", student._id))
            .collect();

          const guardianClasses = classes.filter(c => c.isGuardianLinked === true);

          for (const classItem of guardianClasses) {
            if (!args.dryRun && typeof providerId !== 'string') {
              await ctx.db.patch(classItem._id, {
                providerId,
                // Keep isGuardianLinked for now (rollback safety)
              });
            }
            classesUpdated++;
          }
        }

        if (!args.dryRun) {
          console.log(`  Updated ${classesUpdated} classes`);
        } else {
          console.log(`  [DRY RUN] Would update ${classesUpdated} classes`);
        }

        migrationLog.push({
          guardianId: guardian._id,
          guardianUsername: guardian.username,
          providerId: args.dryRun ? "DRY_RUN" : providerId,
          studentsUpdated,
          classesUpdated,
          status: "success",
        });

      } catch (err) {
        const error = err as Error;
        console.error(`  Error processing guardian ${guardian.username}:`, error);
        errors.push({
          guardianId: guardian._id,
          guardianUsername: guardian.username,
          error: error.message,
        });
        migrationLog.push({
          guardianId: guardian._id,
          guardianUsername: guardian.username,
          providerId: null,
          studentsUpdated: 0,
          classesUpdated: 0,
          status: "failed",
          error: error.message,
        });
      }
    }

    // 4. Handle orphan students (no schoolId, providerId, or guardianId)
    console.log("\n=== Processing Orphan Students ===");
    const allStudents = await ctx.db.query("students").collect();
    const orphanStudents = allStudents.filter(s => 
      !s.schoolId && !s.providerId && !s.guardianId
    );

    console.log(`Found ${orphanStudents.length} orphan students needing pseudo-provider`);

    if (orphanStudents.length > 0) {
      // Create single pseudo-provider for all orphan students
      if (!args.dryRun && !pseudoProviderCreated) {
        pseudoProviderId = await ctx.db.insert("providers", {
          name: "{Teacher'sPVTclass}",
          nameTh: "{ชั้นเรียนส่วนตัวของครู}",
          category: "personal",
          createdBy: args.adminId,
          isActive: true,
          createdAt: Date.now(),
          isAutoGenerated: true, // Auto-generated pseudo-provider
        });
        pseudoProviderCreated = true;
        console.log(`  Created pseudo-provider: ${pseudoProviderId}`);
      } else if (args.dryRun) {
        console.log(`  [DRY RUN] Would create pseudo-provider {Teacher'sPVTclass}`);
      }

      // Update orphan students
      let orphanStudentsUpdated = 0;
      for (const student of orphanStudents) {
        if (!args.dryRun && typeof pseudoProviderId !== 'string') {
          await ctx.db.patch(student._id, {
            providerId: pseudoProviderId,
          });
        }
        orphanStudentsUpdated++;
      }

      if (!args.dryRun) {
        console.log(`  Updated ${orphanStudentsUpdated} orphan students`);
      } else {
        console.log(`  [DRY RUN] Would update ${orphanStudentsUpdated} orphan students`);
      }

      migrationLog.push({
        type: "orphan_students",
        pseudoProviderId: args.dryRun ? "DRY_RUN_PSEUDO" : pseudoProviderId,
        studentsUpdated: orphanStudentsUpdated,
        classesUpdated: 0,
        status: "success",
      });
    }

    // Summary
    const summary = {
      success: errors.length === 0,
      dryRun: args.dryRun || false,
      guardiansProcessed: guardians.length,
      orphanStudentsProcessed: orphanStudents.length,
      pseudoProviderCreated: orphanStudents.length > 0,
      successfulMigrations: migrationLog.filter(m => m.status === "success").length,
      failedMigrations: errors.length,
      migrationLog,
      errors: errors.length > 0 ? errors : undefined,
    };

    if (args.dryRun) {
      console.log("\n=== DRY RUN COMPLETE - No changes made ===");
    } else {
      console.log("\n=== MIGRATION COMPLETE ===");
    }
    console.log(JSON.stringify(summary, null, 2));

    return summary;
  },
});

/**
 * Rollback migration (if needed)
 * Reverses the provider migration by clearing providerId fields
 * 
 * Only use if migration fails or needs to be undone
 */
export const rollbackMigration = mutation({
  args: { 
    adminId: v.id("users"),
    confirm: v.boolean(), // Must be true to execute
  },
  handler: async (ctx, args) => {
    if (!args.confirm) {
      throw new Error("Rollback not confirmed - set confirm: true to proceed");
    }

    // Verify admin
    const admin = await ctx.db.get(args.adminId);
    if (!admin || admin.role !== "admin") {
      throw new Error("Unauthorized: Only admins can run rollback");
    }

    console.log("ROLLING BACK MIGRATION...");

    // Clear providerId from all students that have guardianId
    const students = await ctx.db.query("students").collect();
    const studentsWithBoth = students.filter(s => s.guardianId && s.providerId);

    for (const student of studentsWithBoth) {
      await ctx.db.patch(student._id, {
        providerId: undefined,
      });
    }

    // Clear providerId from all classes that have isGuardianLinked
    const classes = await ctx.db.query("classes").collect();
    const classesWithBoth = classes.filter(c => c.isGuardianLinked && c.providerId);

    for (const classItem of classesWithBoth) {
      await ctx.db.patch(classItem._id, {
        providerId: undefined,
      });
    }

    // Delete auto-generated pseudo-provider
    const providers = await ctx.db.query("providers").collect();
    const pseudoProvider = providers.find(p => p.isAutoGenerated === true && p.name === "{Teacher'sPVTclass}");
    if (pseudoProvider) {
      await ctx.db.delete(pseudoProvider._id);
      console.log("Deleted pseudo-provider");
    }

    console.log("ROLLBACK COMPLETE");

    return {
      success: true,
      studentsRolledBack: studentsWithBoth.length,
      classesRolledBack: classesWithBoth.length,
      pseudoProviderDeleted: !!pseudoProvider,
    };
  },
});

/**
 * Clean up deprecated fields after successful migration
 * This should ONLY be run after:
 * 1. Migration is complete
 * 2. System is verified working with new structure
 * 3. Backup is confirmed safe
 * 
 * WARNING: This is destructive and cannot be undone!
 */
export const cleanupDeprecatedFields = mutation({
  args: {
    adminId: v.id("users"),
    confirm: v.boolean(), // Must be true to execute
    phase: v.union(
      v.literal("students"), // Clean guardianId from students
      v.literal("classes"),  // Clean isGuardianLinked from classes
      v.literal("all")       // Clean both
    ),
  },
  handler: async (ctx, args) => {
    if (!args.confirm) {
      throw new Error("Cleanup not confirmed - set confirm: true to proceed");
    }

    // Verify admin
    const admin = await ctx.db.get(args.adminId);
    if (!admin || admin.role !== "admin") {
      throw new Error("Unauthorized: Only admins can run cleanup");
    }

    console.log(`CLEANUP PHASE: ${args.phase}`);

    let studentsUpdated = 0;
    let classesUpdated = 0;

    // Clean students
    if (args.phase === "students" || args.phase === "all") {
      console.log("Cleaning guardianId from students...");
      const students = await ctx.db.query("students").collect();
      const studentsWithGuardianId = students.filter(s => s.guardianId !== undefined);

      for (const student of studentsWithGuardianId) {
        // Only clean if student has providerId (migration complete)
        if (student.providerId) {
          await ctx.db.patch(student._id, {
            guardianId: undefined,
          });
          studentsUpdated++;
        } else {
          console.warn(`  Skipping student ${student._id} - no providerId set`);
        }
      }
      console.log(`  Cleaned ${studentsUpdated} students`);
    }

    // Clean classes
    if (args.phase === "classes" || args.phase === "all") {
      console.log("Cleaning isGuardianLinked from classes...");
      const classes = await ctx.db.query("classes").collect();
      const classesWithGuardianLinked = classes.filter(c => c.isGuardianLinked !== undefined);

      for (const classItem of classesWithGuardianLinked) {
        // Only clean if class has providerId (migration complete)
        if (classItem.providerId) {
          await ctx.db.patch(classItem._id, {
            isGuardianLinked: undefined,
          });
          classesUpdated++;
        } else {
          console.warn(`  Skipping class ${classItem._id} - no providerId set`);
        }
      }
      console.log(`  Cleaned ${classesUpdated} classes`);
    }

    console.log("CLEANUP COMPLETE");

    return {
      success: true,
      phase: args.phase,
      studentsUpdated,
      classesUpdated,
      warning: "Deprecated fields removed - ensure system is working before proceeding",
    };
  },
});

/**
 * Verification query to check cleanup status
 */
export const verifyCleanup = query({
  args: {},
  handler: async (ctx) => {
    const allStudents = await ctx.db.query("students").collect();
    const studentsWithGuardianId = allStudents.filter(s => s.guardianId !== undefined);
    const studentsWithProviderId = allStudents.filter(s => s.providerId !== undefined);

    const allClasses = await ctx.db.query("classes").collect();
    const classesWithGuardianLinked = allClasses.filter(c => c.isGuardianLinked !== undefined);
    const classesWithProviderId = allClasses.filter(c => c.providerId !== undefined);

    const allUsers = await ctx.db.query("users").collect();
    const guardianUsers = allUsers.filter(u => u.role === "guardian");

    const allProviders = await ctx.db.query("providers").collect();
    const guardianProviders = allProviders.filter(p => p.category === "guardian");
    const pseudoProviders = allProviders.filter(p => p.isAutoGenerated === true);

    return {
      students: {
        total: allStudents.length,
        withGuardianId: studentsWithGuardianId.length,
        withProviderId: studentsWithProviderId.length,
        cleanupComplete: studentsWithGuardianId.length === 0,
      },
      classes: {
        total: allClasses.length,
        withGuardianLinked: classesWithGuardianLinked.length,
        withProviderId: classesWithProviderId.length,
        cleanupComplete: classesWithGuardianLinked.length === 0,
      },
      users: {
        guardianUsers: guardianUsers.length,
        note: guardianUsers.length > 0 ? "Guardian users still exist - consider manual cleanup" : "No guardian users",
      },
      providers: {
        guardianProviders: guardianProviders.length,
        pseudoProviders: pseudoProviders.length,
      },
      overallStatus: 
        studentsWithGuardianId.length === 0 && 
        classesWithGuardianLinked.length === 0
          ? "CLEAN - Migration complete"
          : "INCOMPLETE - Deprecated fields still exist",
    };
  },
});
