import { internalMutation, internalAction } from "./_generated/server";
import { v } from "convex/values";

/**
 * Migration mutations for schema v2
 * These work with the CURRENT schema (schema.ts) to transform data
 * so it's compatible with schemaV2.ts after migration.
 */

const createMigrations = () => {
  return {
    migrateUsers: internalMutation({
      args: { batchSize: v.optional(v.number()) },
      handler: async (
        ctx: any,
        { batchSize = 100 }: { batchSize?: number },
      ) => {
        let migrated = 0;
        const users = await ctx.db
          .query("users")
          .filter((q: any) => q.eq(q.field("role"), "guardian"))
          .take(100);
        for (const user of users) {
          await ctx.db.patch(user._id, { role: "teacher" });
          migrated++;
        }
        return { migrated };
      },
    }),

    migrateClasses: internalMutation({
      args: { batchSize: v.optional(v.number()) },
      handler: async (
        ctx: any,
        { batchSize = 100 }: { batchSize?: number },
      ) => {
        let migrated = 0;
        const classes = await ctx.db.query("classes").take(100);
        for (const classDoc of classes) {
          const patches: Record<string, unknown> = {};
          let needsPatch = false;
          if (classDoc.subject || classDoc.subjectTh) {
            patches.subject = {
              en: classDoc.subject || "",
              th: classDoc.subjectTh || "",
            };
            needsPatch = true;
          }
          if (classDoc.lessonTopic || classDoc.lessonTopicTh) {
            patches.lessonTopic = {
              en: classDoc.lessonTopic || "",
              th: classDoc.lessonTopicTh || "",
            };
            needsPatch = true;
          }
          if (classDoc.materials || classDoc.materialsTh) {
            patches.materials = {
              en: classDoc.materials || "",
              th: classDoc.materialsTh || "",
            };
            needsPatch = true;
          }
          if (classDoc.preparationNotes || classDoc.preparationNotesTh) {
            patches.preparationNotes = {
              en: classDoc.preparationNotes || "",
              th: classDoc.preparationNotesTh || "",
            };
            needsPatch = true;
          }
          if (
            classDoc.providerId &&
            classDoc.status === "approved" &&
            !classDoc.approvalSource
          ) {
            patches.approvalSource = "auto_provider";
            needsPatch = true;
          }
          if (needsPatch) await ctx.db.patch(classDoc._id, patches);
          migrated++;
        }
        return { migrated };
      },
    }),

    migrateProviders: internalMutation({
      args: { batchSize: v.optional(v.number()) },
      handler: async (
        ctx: any,
        { batchSize = 100 }: { batchSize?: number },
      ) => {
        let migrated = 0;
        const providers = await ctx.db
          .query("providers")
          .filter((q: any) => q.eq(q.field("isAutoGenerated"), undefined))
          .take(100);
        for (const provider of providers) {
          await ctx.db.patch(provider._id, { isAutoGenerated: false });
          migrated++;
        }
        return { migrated };
      },
    }),

    migrateLocations: internalMutation({
      args: { batchSize: v.optional(v.number()) },
      handler: async (
        ctx: any,
        { batchSize = 100 }: { batchSize?: number },
      ) => {
        let migrated = 0;
        const locations = await ctx.db
          .query("locations")
          .filter((q: any) => q.eq(q.field("type"), "guardian"))
          .take(100);
        for (const location of locations) {
          await ctx.db.patch(location._id, { type: "private" });
          migrated++;
        }
        return { migrated };
      },
    }),

    migrateStudents: internalMutation({
      args: { batchSize: v.optional(v.number()) },
      handler: async (
        ctx: any,
        { batchSize = 100 }: { batchSize?: number },
      ) => {
        let migrated = 0;
        const students = await ctx.db.query("students").take(100);
        for (const student of students) {
          const patches: Record<string, unknown> = {};
          let needsPatch = false;
          if (!student.providerId) {
            if (student.schoolId) {
              const school = await ctx.db.get(student.schoolId);
              if (school?.moderatorId) {
                const provider = await ctx.db
                  .query("providers")
                  .filter((q: any) =>
                    q.eq(q.field("createdBy"), school.moderatorId),
                  )
                  .filter((q: any) => q.eq(q.field("category"), "guardian"))
                  .first();
                if (provider) {
                  patches.providerId = provider._id;
                  needsPatch = true;
                }
              }
            } else if (student.guardianId) {
              const ownerId = student.createdBy || student.guardianId;
              if (ownerId) {
                const providerId = await ctx.db.insert("providers", {
                  name: "My Private Students",
                  nameTh: "นักเรียนส่วนตัวของฉัน",
                  category: "personal",
                  createdBy: ownerId,
                  isActive: true,
                  createdAt: Date.now(),
                  isAutoGenerated: false,
                });
                patches.providerId = providerId;
                needsPatch = true;
              }
            }
            if (needsPatch) {
              await ctx.db.patch(student._id, patches);
            }
            migrated++;
          }
        }
        return { migrated };
      },
    }),
  };
};

const migrations = createMigrations();

export const runAllMigrations = internalAction({
  handler: async (ctx: any) => {
    const results = {
      users: await ctx.runMutation(migrations.migrateUsers),
      students: await ctx.runMutation(migrations.migrateStudents),
      classes: await ctx.runMutation(migrations.migrateClasses),
      providers: await ctx.runMutation(migrations.migrateProviders),
      locations: await ctx.runMutation(migrations.migrateLocations),
    };
    return results;
  },
});

export const {
  migrateUsers,
  migrateClasses,
  migrateProviders,
  migrateLocations,
  migrateStudents,
} = migrations;

export { migrations };
