import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    username: v.string(),
    passwordHash: v.string(),
    role: v.union(
      v.literal("teacher"),
      v.literal("moderator"),
      v.literal("admin")
    ),
    schoolId: v.optional(v.id("schools")),
    requirePasswordChange: v.boolean(),
    createdAt: v.number(),
    preferredLanguage: v.optional(v.union(v.literal("en"), v.literal("th"))),
    failedLoginAttempts: v.optional(v.number()),
    accountLockedUntil: v.optional(v.number()),
    lastSuccessfulLogin: v.optional(v.number()),
    loginHistory: v.optional(v.array(v.object({
      timestamp: v.number(),
      userAgent: v.string(),
      deviceType: v.string(),
      platform: v.string(),
      browser: v.string(),
    }))),
    deletedAt: v.optional(v.number()),
  })
    .index("by_username", ["username"])
    .index("by_school", ["schoolId"])
    .index("by_role", ["role"]),

  schools: defineTable({
    name: v.string(),
    nameTh: v.string(),
    moderatorId: v.optional(v.id("users")),
    createdAt: v.number(),
    district: v.optional(v.string()),
    districtTh: v.optional(v.string()),
    province: v.optional(v.string()),
    provinceTh: v.optional(v.string()),
    deletedAt: v.optional(v.number()),
  })
    .index("by_moderator", ["moderatorId"])
    .index("by_province", ["province"]),

  providers: defineTable({
    name: v.string(),
    nameTh: v.string(),
    category: v.union(
      v.literal("personal"),
      v.literal("private"),
      v.literal("language_school"),
      v.literal("educational_camp")
    ),
    createdBy: v.id("users"),
    schoolId: v.optional(v.id("schools")),
    isActive: v.boolean(),
    createdAt: v.number(),
    isAutoGenerated: v.optional(v.boolean()),
    deletedAt: v.optional(v.number()),
  })
    .index("by_created_by", ["createdBy"])
    .index("by_category", ["category"])
    .index("by_school", ["schoolId"]),

  students: defineTable({
    firstName: v.string(),
    lastName: v.string(),
    studentId: v.string(),
    schoolId: v.optional(v.id("schools")),
    providerId: v.id("providers"),
    grade: v.string(),
    class: v.optional(v.string()),
    parentName: v.optional(v.string()),
    parentPhone: v.optional(v.string()),
    parentEmail: v.optional(v.string()),
    secondaryParentName: v.optional(v.string()),
    secondaryParentPhone: v.optional(v.string()),
    nickname: v.optional(v.string()),
    dateOfBirth: v.optional(v.number()),
    allergies: v.optional(v.string()),
    specialNeeds: v.optional(v.string()),
    medicalNotes: v.optional(v.string()),
    notes: v.optional(v.string()),
    provinceCode: v.optional(v.string()),
    districtName: v.optional(v.string()),
    isDeleted: v.optional(v.boolean()),
    deletedAt: v.optional(v.number()),
    deletedBy: v.optional(v.id("users")),
    deletionReason: v.optional(v.string()),
    createdBy: v.optional(v.id("users")),
    createdAt: v.number(),
  })
    .index("by_student_id", ["studentId"])
    .index("by_provider", ["providerId"])
    .index("by_school", ["schoolId"])
    .index("by_grade_and_class", ["grade", "class"])
    .index("by_province", ["provinceCode"])
    .index("by_district", ["districtName"]),

  classes: defineTable({
    teacherId: v.id("users"),
    schoolId: v.optional(v.id("schools")),
    providerId: v.optional(v.id("providers")),
    studentId: v.id("students"),
    additionalStudentIds: v.optional(v.array(v.id("students"))),
    locationId: v.optional(v.id("locations")),
    subject: v.optional(v.object({ en: v.string(), th: v.string() })),
    lessonTopic: v.optional(v.object({ en: v.string(), th: v.string() })),
    materials: v.optional(v.object({ en: v.string(), th: v.string() })),
    preparationNotes: v.optional(v.object({ en: v.string(), th: v.string() })),
    scheduledDate: v.number(),
    duration: v.optional(v.number()),
    classType: v.optional(v.union(
      v.literal("regular"),
      v.literal("makeup"),
      v.literal("assessment"),
      v.literal("trial")
    )),
    status: v.union(
      v.literal("pending"),
      v.literal("acknowledged"),
      v.literal("approved"),
      v.literal("rejected"),
      v.literal("completed"),
      v.literal("cancelled")
    ),
    approvedByUserId: v.optional(v.id("users")),
    approvedByUsername: v.optional(v.string()),
    approvedAt: v.optional(v.number()),
    approvalSource: v.optional(v.union(
      v.literal("moderator"),
      v.literal("admin"),
      v.literal("auto_provider"),
      v.literal("system")
    )),
    flaggedForReview: v.optional(v.boolean()),
    includeInReports: v.optional(v.boolean()),
    reviewNotes: v.optional(v.object({ en: v.string(), th: v.string() })),
    flaggedBy: v.optional(v.id("users")),
    flaggedAt: v.optional(v.number()),
    isEdited: v.optional(v.boolean()),
    lastEditedAt: v.optional(v.number()),
    lastEditedBy: v.optional(v.id("users")),
    editHistory: v.optional(v.array(v.object({
      editedAt: v.number(),
      editedBy: v.id("users"),
      editedByName: v.string(),
      editedByRole: v.string(),
      changes: v.array(v.object({
        field: v.string(),
        oldValue: v.string(),
        newValue: v.string(),
      })),
    }))),
    loggedAt: v.optional(v.number()),
    actualDuration: v.optional(v.number()),
    attendance: v.optional(v.union(
      v.literal("present"),
      v.literal("absent"),
      v.literal("late")
    )),
    createdAt: v.number(),
    deletedAt: v.optional(v.number()),
  })
    .index("by_teacher", ["teacherId"])
    .index("by_school", ["schoolId"])
    .index("by_provider", ["providerId"])
    .index("by_student", ["studentId"])
    .index("by_status", ["status"])
    .index("by_scheduled_date", ["scheduledDate"])
    .index("by_teacher_and_date", ["teacherId", "scheduledDate"])
    .index("by_teacher_and_status", ["teacherId", "status"])
    .index("by_provider_and_date", ["providerId", "scheduledDate"])
    .index("by_completed_date", ["loggedAt"]),

  locations: defineTable({
    name: v.string(),
    nameTh: v.string(),
    schoolId: v.optional(v.id("schools")),
    providerId: v.optional(v.id("providers")),
    type: v.optional(v.union(v.literal("school"), v.literal("private"))),
    isActive: v.boolean(),
    isPending: v.optional(v.boolean()),
    requestedBy: v.optional(v.id("users")),
    approvedBy: v.optional(v.id("users")),
    createdAt: v.number(),
    deletedAt: v.optional(v.number()),
  })
    .index("by_school", ["schoolId"])
    .index("by_provider", ["providerId"])
    .index("by_active", ["isActive"]),

  notifications: defineTable({
    title: v.string(),
    titleTh: v.string(),
    message: v.string(),
    messageTh: v.string(),
    type: v.union(v.literal("info"), v.literal("success"), v.literal("warning"), v.literal("error")),
    userId: v.optional(v.union(v.string(), v.id("users"))),
    read: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_created_at", ["createdAt"])
    .index("by_read", ["read"]),

  messages: defineTable({
    senderId: v.id("users"),
    recipientId: v.optional(v.id("users")),
    schoolId: v.optional(v.id("schools")),
    groupId: v.optional(v.id("groups")),
    content: v.string(),
    contentTh: v.string(),
    isGroupMessage: v.boolean(),
    read: v.boolean(),
    acknowledged: v.boolean(),
    createdAt: v.number(),
    attachmentStorageId: v.optional(v.id("_storage")),
    attachmentName: v.optional(v.string()),
    attachmentType: v.optional(v.string()),
    attachmentSize: v.optional(v.number()),
    isActive: v.optional(v.boolean()),
  })
    .index("by_sender", ["senderId"])
    .index("by_recipient", ["recipientId"])
    .index("by_school", ["schoolId"])
    .index("by_group", ["groupId"])
    .index("by_created_at", ["createdAt"])
    .index("by_conversation", ["senderId", "recipientId"])
    .index("by_school_and_date", ["schoolId", "createdAt"])
    .index("by_active", ["isActive"])
    .index("by_school_and_active", ["schoolId", "isActive"]),

  groups: defineTable({
    name: v.string(),
    nameTh: v.string(),
    schoolId: v.id("schools"),
    creatorId: v.id("users"),
    memberIds: v.array(v.id("users")),
    createdAt: v.number(),
  })
    .index("by_school", ["schoolId"])
    .index("by_creator", ["creatorId"])
    .index("by_created_at", ["createdAt"]),

  teacherResources: defineTable({
    title: v.string(),
    titleTh: v.string(),
    description: v.string(),
    descriptionTh: v.string(),
    url: v.string(),
    category: v.string(),
    categoryTh: v.string(),
    order: v.number(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
    createdBy: v.id("users"),
  })
    .index("by_order", ["order"])
    .index("by_active", ["isActive"])
    .index("by_category", ["category"])
    .index("by_created_at", ["createdAt"]),

  teacherLogs: defineTable({
    teacherId: v.id("users"),
    schoolId: v.id("schools"),
    action: v.string(),
    actionTh: v.string(),
    details: v.string(),
    detailsTh: v.string(),
    relatedClassId: v.optional(v.id("classes")),
    relatedStudentId: v.optional(v.id("students")),
    acknowledged: v.optional(v.boolean()),
    acknowledgedBy: v.optional(v.id("users")),
    acknowledgedAt: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_teacher", ["teacherId"])
    .index("by_school", ["schoolId"])
    .index("by_action", ["action"])
    .index("by_created_at", ["createdAt"])
    .index("by_teacher_and_date", ["teacherId", "createdAt"])
    .index("by_school_and_date", ["schoolId", "createdAt"])
    .index("by_acknowledged", ["acknowledged"])
    .index("by_school_and_acknowledged", ["schoolId", "acknowledged"]),

  postClassNotes: defineTable({
    classId: v.id("classes"),
    teacherId: v.id("users"),
    studentId: v.id("students"),
    schoolId: v.optional(v.id("schools")),
    notes: v.optional(v.object({ en: v.string(), th: v.string() })),
    attendance: v.union(v.literal("present"), v.literal("absent"), v.literal("late")),
    behavior: v.optional(v.union(v.literal("excellent"), v.literal("good"), v.literal("fair"), v.literal("needs_improvement"))),
    participation: v.optional(v.union(v.literal("excellent"), v.literal("good"), v.literal("fair"), v.literal("needs_improvement"))),
    homework: v.optional(v.object({ en: v.string(), th: v.string() })),
    createdAt: v.number(),
    skipped: v.boolean(),
  })
    .index("by_class", ["classId"])
    .index("by_teacher", ["teacherId"])
    .index("by_student", ["studentId"])
    .index("by_school", ["schoolId"])
    .index("by_created_at", ["createdAt"])
    .index("by_class_and_student", ["classId", "studentId"])
    .index("by_student_and_created_at", ["studentId", "createdAt"]),

  appUpdates: defineTable({
    version: v.string(),
    releaseDate: v.number(),
    title: v.string(),
    titleTh: v.string(),
    description: v.string(),
    descriptionTh: v.string(),
    features: v.array(v.object({
      title: v.string(),
      titleTh: v.string(),
      description: v.string(),
      descriptionTh: v.string(),
      icon: v.string(),
    })),
    isActive: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_active", ["isActive"])
    .index("by_release_date", ["releaseDate"])
    .index("by_version", ["version"]),

  userUpdateViews: defineTable({
    userId: v.id("users"),
    updateId: v.id("appUpdates"),
    viewedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_update", ["updateId"])
    .index("by_user_and_update", ["userId", "updateId"]),

  adminContactRequests: defineTable({
    userId: v.id("users"),
    userRole: v.string(),
    username: v.string(),
    requestType: v.union(v.literal("general"), v.literal("feature_suggestion"), v.literal("bug_report"), v.literal("help_request"), v.literal("notification_window_request")),
    subject: v.string(),
    subjectTh: v.string(),
    message: v.string(),
    messageTh: v.string(),
    status: v.union(v.literal("pending"), v.literal("in_progress"), v.literal("resolved"), v.literal("dismissed")),
    adminNotes: v.optional(v.string()),
    adminNotesTh: v.optional(v.string()),
    resolvedBy: v.optional(v.id("users")),
    resolvedAt: v.optional(v.number()),
    createdAt: v.number(),
    attachmentStorageId: v.optional(v.id("_storage")),
    attachmentName: v.optional(v.string()),
    attachmentType: v.optional(v.string()),
    attachmentSize: v.optional(v.number()),
    deletedAt: v.optional(v.number()),
  })
    .index("by_user", ["userId"])
    .index("by_status", ["status"])
    .index("by_created_at", ["createdAt"]),

  cancellationRequests: defineTable({
    classId: v.id("classes"),
    teacherId: v.id("users"),
    schoolId: v.optional(v.id("schools")),
    requestType: v.union(v.literal("cancel"), v.literal("postpone")),
    reason: v.string(),
    reasonTh: v.string(),
    newScheduledDate: v.optional(v.number()),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    createdAt: v.number(),
    resolvedAt: v.optional(v.number()),
    resolvedBy: v.optional(v.id("users")),
    reviewNotes: v.optional(v.string()),
    reviewNotesTh: v.optional(v.string()),
  })
    .index("by_class", ["classId"])
    .index("by_teacher", ["teacherId"])
    .index("by_school", ["schoolId"])
    .index("by_status", ["status"])
    .index("by_created_at", ["createdAt"])
    .index("by_class_and_status", ["classId", "status"]),

  events: defineTable({
    title: v.string(),
    titleTh: v.string(),
    description: v.string(),
    descriptionTh: v.string(),
    startDate: v.number(),
    endDate: v.number(),
    allDay: v.boolean(),
    color: v.optional(v.string()),
    schoolId: v.optional(v.id("schools")),
    createdBy: v.id("users"),
    isActive: v.boolean(),
    createdAt: v.number(),
    deletedAt: v.optional(v.number()),
  })
    .index("by_school", ["schoolId"])
    .index("by_date_range", ["startDate", "endDate"])
    .index("by_active", ["isActive"]),

  teacherClassCountCycles: defineTable({
    teacherId: v.id("users"),
    schoolId: v.optional(v.id("schools")),
    cycleName: v.string(),
    startDate: v.number(),
    endDate: v.number(),
    isActive: v.boolean(),
    createdBy: v.id("users"),
    createdAt: v.number(),
    deletedAt: v.optional(v.number()),
  })
    .index("by_teacher", ["teacherId"])
    .index("by_school", ["schoolId"])
    .index("by_active", ["isActive"])
    .index("by_school_and_active", ["schoolId", "isActive"]),
});