import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { AuditActions, AuditTargetTypes, logAudit } from "./auditHelpers";
import { checkRateLimit, validateLength } from "./rateLimit";

// Helper function to generate unique ID for SCHOOL students
function generateStudentId(firstName: string, lastName: string, schoolId: string): string {
  const timestamp = Date.now().toString(36);
  const nameHash = `${firstName.substring(0, 2)}${lastName.substring(0, 2)}`.toUpperCase();
  const schoolHash = schoolId.substring(0, 4).toUpperCase();
  const random = Math.random().toString(36).substring(2, 6).toUpperCase();

  return `${schoolHash}-${nameHash}-${timestamp}-${random}`;
}

// Query to list students
export const list = query({
  args: {
    schoolId: v.optional(v.id("schools")),
  },
  handler: async (ctx, args) => {
    if (args.schoolId) {
      return await ctx.db
        .query("students")
        .withIndex("by_school", (q) => q.eq("schoolId", args.schoolId!))
        .collect();
    }

    return await ctx.db.query("students").collect();
  },
});

// Query to get student by ID
export const getById = query({
  args: {
    id: v.id("students"),
  },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.id);
  },
});

// Query to get student by student ID
export const getByStudentId = query({
  args: {
    studentId: v.string(),
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("students")
      .withIndex("by_student_id", (q) => q.eq("studentId", args.studentId))
      .first();
  },
});

// Query to get students by guardian
export const getByGuardian = query({
  args: {
    guardianName: v.string(),
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("students")
      .withIndex("by_guardian", (q) => q.eq("guardianName", args.guardianName))
      .collect();
  },
});

// Mutation to create a new student
export const create = mutation({
  args: {
    firstName: v.string(),
    lastName: v.string(),
    schoolId: v.optional(v.id("schools")), // Optional for provider-linked students
    providerId: v.optional(v.id("providers")), // Provider ID - auto-creates if teacher self-reference
    autoCreateProvider: v.optional(v.boolean()), // NEW - Auto-create "Evan'sPVTclass" provider
    guardianTitle: v.optional(v.string()), // Relationship description
    grade: v.string(), // Grade level (K1, K2, K3)
    class: v.optional(v.string()), // Class number (/1, /2, ..., /10)
    guardianName: v.optional(v.string()),
    guardianPhone: v.optional(v.string()),
    guardianEmail: v.optional(v.string()),
    createdBy: v.id("users"), // Teacher who created the student
    // Optional fields
    nickname: v.optional(v.string()),
    dateOfBirth: v.optional(v.number()), // Timestamp - REQUIRED for provider students
    // NEW LOCATION FIELDS - At least 2 required for duplicate detection (provider students)
    district: v.optional(v.string()), // District (e.g., "Bang Rak")
    province: v.optional(v.string()), // Province (e.g., "Bangkok")
    area: v.optional(v.string()), // Specific area (e.g., "Thonglor")
    parentName: v.optional(v.string()),
    parentPhone: v.optional(v.string()),
    parentEmail: v.optional(v.string()),
    secondaryParentName: v.optional(v.string()),
    secondaryParentPhone: v.optional(v.string()),
    allergies: v.optional(v.string()),
    specialNeeds: v.optional(v.string()),
    medicalNotes: v.optional(v.string()),
    notes: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // ✅ RATE LIMIT: Prevent accidental rapid student creation (20 per minute - soft limit)
    await checkRateLimit(ctx, {
      key: `create-student:${args.createdBy}`,
      limit: 20,
      windowMs: 60000, // 1 minute
    });

    // ✅ SECURITY: Verify user permissions
    const creator = await ctx.db.get(args.createdBy);
    if (!creator) {
      throw new Error("Creator user not found");
    }

    // NEW: Auto-create "Evan'sPVTclass" provider if requested (teacher self-reference)
    let finalProviderId = args.providerId;
    if (args.autoCreateProvider && !args.providerId && !args.schoolId) {
      // Check if teacher already has an "Evan'sPVTclass" provider
      const existingProvider = await ctx.db
        .query("providers")
        .withIndex("by_created_by", (q) => q.eq("createdBy", args.createdBy))
        .filter((q) => q.eq(q.field("isPrivateClassProvider"), true))
        .first();

      if (existingProvider) {
        finalProviderId = existingProvider._id;
      } else {
        // Create new "Evan'sPVTclass" provider
        finalProviderId = await ctx.db.insert("providers", {
          name: "Evan'sPVTclass",
          nameTh: "คลาสส่วนตัวของอีวาน",
          category: "personal",
          createdBy: args.createdBy,
          isActive: true,
          isAutoGenerated: true,
          isPrivateClassProvider: true,
          createdAt: Date.now(),
        });
      }
    }

    // ✅ VALIDATION - Student must have EITHER schoolId OR providerId (after auto-creation)
    const hasSchool = !!args.schoolId;
    const hasProvider = !!finalProviderId;

    // If both school and provider are provided, reject
    if (hasSchool && hasProvider) {
      throw new Error("Student cannot be linked to both a school and a provider. Please choose one.");
    }

    // Must have either school or provider
    if (!hasSchool && !hasProvider) {
      throw new Error("Student must be linked to either a school or provider");
    }

    // ✅ SECURITY: Role-based access control
    if (args.schoolId) {
      // School-linked students require school access
      if (creator.role === "teacher" || creator.role === "moderator") {
        // Teachers and moderators can only create students for their own school
        if (creator.schoolId !== args.schoolId) {
          throw new Error("Unauthorized: Cannot create students for other schools");
        }
      } else if (creator.role !== "admin") {
        throw new Error("Unauthorized: Only teachers, moderators, and admins can create school-linked students");
      }
    } else if (finalProviderId) {
      // Provider-linked students (teachers and admins only)
      if (creator.role === "moderator") {
        throw new Error("Unauthorized: Moderators cannot create provider-linked students");
      }

      // Verify provider exists and teacher has access
      const provider = await ctx.db.get(finalProviderId);
      if (!provider) {
        throw new Error("Provider not found");
      }

      // Teachers can only use their own providers, admins can use any
      if (creator.role === "teacher" && provider.createdBy !== creator._id) {
        throw new Error("Unauthorized: You can only create students for providers you created");
      }
    }

    // ✅ SECURITY: Input validation - student names max 100 chars
    validateLength(args.firstName, "First name", 100, 1);
    // Allow empty lastName for Thai students who use single names/nicknames
    if (args.lastName) {
      validateLength(args.lastName, "Last name", 100, 0);
    }
    if (args.nickname) validateLength(args.nickname, "Nickname", 100, 0);
    if (args.notes) validateLength(args.notes, "Notes", 2000, 0);
    if (args.area) validateLength(args.area, "Area", 100, 0);
    if (args.district) validateLength(args.district, "District", 100, 0);
    if (args.province) validateLength(args.province, "Province", 100, 0);

    // Validate: class is required for school-linked students
    if (args.schoolId && !args.class) {
      throw new Error("Class is required for students linked to a school");
    }

    // NEW: Validate provider student requirements
    if (finalProviderId && !args.grade) {
      throw new Error("Grade is required for provider-linked students");
    }

    // NEW: Enforce at least 2 location fields for duplicate detection (provider students only)
    if (finalProviderId) {
      const locationFieldCount = [args.district, args.province, args.area].filter(Boolean).length;
      if (locationFieldCount < 2) {
        throw new Error("Provider students must have at least 2 location fields (district, province, or area) for duplicate detection");
      }
    }

    // ✅ PREVENT DUPLICATES: Check if student already exists with same name + grade + class + school
    if (args.schoolId) {
      const duplicateCheck = await ctx.db
        .query("students")
        .withIndex("by_school", (q) => q.eq("schoolId", args.schoolId!))
        .collect();

      const duplicate = duplicateCheck.find(
        (s) =>
          s.firstName.toLowerCase() === args.firstName.toLowerCase() &&
          (s.lastName || "").toLowerCase() === (args.lastName || "").toLowerCase() &&
          s.grade === args.grade &&
          s.class === args.class
      );

      if (duplicate) {
        throw new Error(
          `Student "${args.firstName}${args.lastName ? " " + args.lastName : ""}" already exists in ${args.grade}${args.class}`
        );
      }
    }

    // NEW: ✅ PREVENT DUPLICATES for provider students (name + grade + location fields)
    if (finalProviderId) {
      const providerStudents = await ctx.db
        .query("students")
        .withIndex("by_provider", (q) => q.eq("providerId", finalProviderId!))
        .collect();

      // Check for duplicate based on name, grade, and location overlap
      const providerDuplicate = providerStudents.find((s) => {
        // Name and grade must match
        if (
          s.firstName.toLowerCase() !== args.firstName.toLowerCase() ||
          (s.lastName || "").toLowerCase() !== (args.lastName || "").toLowerCase() ||
          s.grade !== args.grade
        ) {
          return false;
        }

        // Check location field overlap (at least 2 must match)
        const locationMatches = [
          s.district && args.district && s.district.toLowerCase() === args.district.toLowerCase(),
          s.province && args.province && s.province.toLowerCase() === args.province.toLowerCase(),
          s.area && args.area && s.area.toLowerCase() === args.area.toLowerCase(),
        ].filter(Boolean).length;

        return locationMatches >= 2;
      });

      if (providerDuplicate) {
        const provider = await ctx.db.get(finalProviderId);
        const locationInfo = [args.district, args.province, args.area].filter(Boolean).join(", ");
        throw new Error(
          `Student "${args.firstName}${args.lastName ? " " + args.lastName : ""}" already exists in ${args.grade} for provider "${provider?.name || "Unknown"}" with matching location (${locationInfo}) (ID: ${providerDuplicate.studentId})`
        );
      }
    }

    // Generate unique student ID based on student type
    let studentId: string;

    if (finalProviderId) {
      // Provider student: use provider-based ID with location
      const locationHash = [args.district, args.province, args.area].filter(Boolean).join("-").substring(0, 10).toUpperCase().replace(/[^A-Z0-9]/g, '');
      const timestamp = Date.now().toString(36);
      const nameHash = `${args.firstName.substring(0, 2)}${(args.lastName || "").substring(0, 2)}`.toUpperCase();
      const providerHash = finalProviderId.substring(0, 4).toUpperCase();
      const random = Math.random().toString(36).substring(2, 6).toUpperCase();
      studentId = `${providerHash}-${nameHash}-${locationHash}-${timestamp}-${random}`;
    } else {
      // School student: use school-based ID
      studentId = generateStudentId(args.firstName, args.lastName || "", args.schoolId || "NOSCHOOL");
    }

    // Check for duplicates and regenerate if necessary
    let attempts = 0;
    const maxAttempts = 10;

    while (attempts < maxAttempts) {
      const existing = await ctx.db
        .query("students")
        .withIndex("by_student_id", (q) => q.eq("studentId", studentId))
        .first();

      if (!existing) {
        break;
      }

      // Regenerate with new random component
      if (finalProviderId) {
        const locationHash = [args.district, args.province, args.area].filter(Boolean).join("-").substring(0, 10).toUpperCase().replace(/[^A-Z0-9]/g, '');
        const timestamp = Date.now().toString(36);
        const nameHash = `${args.firstName.substring(0, 2)}${(args.lastName || "").substring(0, 2)}`.toUpperCase();
        const providerHash = finalProviderId.substring(0, 4).toUpperCase();
        const random = Math.random().toString(36).substring(2, 6).toUpperCase();
        studentId = `${providerHash}-${nameHash}-${locationHash}-${timestamp}-${random}`;
      } else {
        studentId = generateStudentId(args.firstName, args.lastName || "", args.schoolId || "NOSCHOOL");
      }
      attempts++;
    }

    if (attempts === maxAttempts) {
      throw new Error("Failed to generate unique student ID after multiple attempts");
    }

    const id = await ctx.db.insert("students", {
      firstName: args.firstName,
      lastName: args.lastName,
      studentId,
      schoolId: args.schoolId,
      providerId: finalProviderId, // Use the final provider ID (auto-created or specified)
      guardianTitle: args.guardianTitle,
      grade: args.grade,
      class: args.class,
      guardianName: args.guardianName,
      guardianPhone: args.guardianPhone,
      guardianEmail: args.guardianEmail,
      acknowledged: true, // No longer need guardian acknowledgement
      createdBy: args.createdBy,
      createdAt: Date.now(),
      // Optional fields
      nickname: args.nickname,
      dateOfBirth: args.dateOfBirth,
      // NEW: Location fields
      district: args.district,
      province: args.province,
      area: args.area,
      parentName: args.parentName,
      parentPhone: args.parentPhone,
      parentEmail: args.parentEmail,
      secondaryParentName: args.secondaryParentName,
      secondaryParentPhone: args.secondaryParentPhone,
      allergies: args.allergies,
      specialNeeds: args.specialNeeds,
      medicalNotes: args.medicalNotes,
      notes: args.notes,
    });

    return { id, studentId };
  },
});

// Mutation to update student
export const update = mutation({
  args: {
    id: v.id("students"),
    updatedBy: v.id("users"), // Required: user making the update
    firstName: v.optional(v.string()),
    lastName: v.optional(v.string()),
    schoolId: v.optional(v.id("schools")),
    providerId: v.optional(v.id("providers")),
    grade: v.optional(v.string()),
    class: v.optional(v.string()),
    guardianTitle: v.optional(v.string()),
    guardianName: v.optional(v.string()),
    guardianPhone: v.optional(v.string()),
    guardianEmail: v.optional(v.string()),
    // Optional fields
    nickname: v.optional(v.string()),
    dateOfBirth: v.optional(v.number()), // Timestamp
    // NEW LOCATION FIELDS
    district: v.optional(v.string()),
    province: v.optional(v.string()),
    area: v.optional(v.string()),
    parentName: v.optional(v.string()),
    parentPhone: v.optional(v.string()),
    parentEmail: v.optional(v.string()),
    secondaryParentName: v.optional(v.string()),
    secondaryParentPhone: v.optional(v.string()),
    allergies: v.optional(v.string()),
    specialNeeds: v.optional(v.string()),
    medicalNotes: v.optional(v.string()),
    notes: v.optional(v.string()),
    // Optional: Client-side performance tracking
    userAgent: v.optional(v.string()),
    screenResolution: v.optional(v.string()),
    timezone: v.optional(v.string()),
    locale: v.optional(v.string()),
    sessionId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const {
      id,
      updatedBy,
      userAgent: _userAgent,
      screenResolution: _screenResolution,
      timezone: _timezone,
      locale: _locale,
      sessionId: _sessionId,
      ...updates
    } = args;

    // ✅ RATE LIMIT: Prevent accidental rapid updates (30 per minute - soft limit)
    await checkRateLimit(ctx, {
      key: `update-student:${updatedBy}`,
      limit: 30,
      windowMs: 60000,
    });

    // Get existing student to validate schoolId requirement
    const student = await ctx.db.get(id);
    if (!student) {
      throw new Error("Student not found");
    }

    // ✅ SECURITY: Verify user permissions
    const user = await ctx.db.get(updatedBy);
    if (!user) {
      throw new Error("User not found");
    }

    // ✅ SECURITY: Role-based access control
    if (user.role === "teacher") {
      // Teachers can modify their own school students OR their provider students
      const isSchoolStudent = !!student.schoolId;
      const isProviderStudent = !!student.providerId;
      
      if (isSchoolStudent && student.schoolId !== user.schoolId) {
        throw new Error("Unauthorized: Cannot modify students from other schools");
      }
      
      if (isProviderStudent) {
        // Verify teacher owns the provider
        const provider = await ctx.db.get(student.providerId);
        if (!provider || provider.createdBy !== user._id) {
          throw new Error("Unauthorized: Cannot modify students from providers you don't own");
        }
      }
    } else if (user.role === "moderator") {
      // Moderators can only modify students from their school
      if (!student.schoolId || student.schoolId !== user.schoolId) {
        throw new Error("Unauthorized: Cannot modify students from other schools");
      }
    } else if (user.role !== "admin") {
      throw new Error("Unauthorized: Insufficient permissions");
    }

    // ✅ SECURITY: Input validation for updated fields
    if (updates.firstName) validateLength(updates.firstName, "First name", 100, 1);
    if (updates.lastName) validateLength(updates.lastName, "Last name", 100, 1);
    if (updates.nickname) validateLength(updates.nickname, "Nickname", 100, 0);
    if (updates.notes) validateLength(updates.notes, "Notes", 2000, 0);
    if (updates.area) validateLength(updates.area, "Area", 100, 0);
    if (updates.district) validateLength(updates.district, "District", 100, 0);
    if (updates.province) validateLength(updates.province, "Province", 100, 0);

    // Validate: class is required for school-linked students
    if (student.schoolId && updates.class === "") {
      throw new Error("Class is required for students linked to a school");
    }

    const filteredUpdates = Object.fromEntries(
      Object.entries(updates).filter(([, v]) => v !== undefined)
    );

    await ctx.db.patch(id, filteredUpdates);

    return { success: true };
  },
});

// Mutation to delete student
export const remove = mutation({
  args: {
    id: v.id("students"),
    deletedBy: v.id("users"), // Required: user deleting the student
    reason: v.string(), // Required: reason for deletion (audit trail)
    // Optional: Client-side performance tracking
    userAgent: v.optional(v.string()),
    screenResolution: v.optional(v.string()),
    timezone: v.optional(v.string()),
    locale: v.optional(v.string()),
    sessionId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const {
      userAgent: _userAgent,
      screenResolution: _screenResolution,
      timezone: _timezone,
      locale: _locale,
      sessionId: _sessionId,
      ...operationArgs
    } = args;

    // ✅ RATE LIMIT: Prevent accidental rapid deletions (10 per minute - more restrictive)
    await checkRateLimit(ctx, {
      key: `delete-student:${operationArgs.deletedBy}`,
      limit: 10,
      windowMs: 60000,
    });

    // Get student details before deletion
    const student = await ctx.db.get(operationArgs.id);
    if (!student) {
      throw new Error("Student not found");
    }

    // ✅ SECURITY: Verify user permissions
    const user = await ctx.db.get(operationArgs.deletedBy);
    if (!user) {
      throw new Error("User not found");
    }

    // ✅ SECURITY: Role-based access control
    if (user.role === "teacher") {
      // Teachers can delete their own school students OR their provider students
      const isSchoolStudent = !!student.schoolId;
      const isProviderStudent = !!student.providerId;
      
      if (isSchoolStudent && student.schoolId !== user.schoolId) {
        throw new Error("Unauthorized: Cannot delete students from other schools");
      }
      
      if (isProviderStudent) {
        // Verify teacher owns the provider
        const provider = await ctx.db.get(student.providerId);
        if (!provider || provider.createdBy !== user._id) {
          throw new Error("Unauthorized: Cannot delete students from providers you don't own");
        }
      }
    } else if (user.role === "moderator") {
      // Moderators can only delete students from their school
      if (!student.schoolId || student.schoolId !== user.schoolId) {
        throw new Error("Unauthorized: Cannot delete students from other schools");
      }
    } else if (user.role !== "admin") {
      throw new Error("Unauthorized: Insufficient permissions");
    }

    // Check for active classes with this student
    const activeClasses = await ctx.db
      .query("classes")
      .withIndex("by_student", (q) => q.eq("studentId", operationArgs.id))
      .collect();

    if (activeClasses.length > 0) {
      // Get count by status
      const pendingOrApproved = activeClasses.filter(
        (c) => c.status === "pending" || c.status === "acknowledged" || c.status === "approved"
      ).length;

      if (pendingOrApproved > 0) {
        throw new Error(
          `Cannot delete student with ${pendingOrApproved} active/pending classes. Please cancel or complete classes first.`
        );
      }
    }

    // ✅ CRITICAL: Audit logging BEFORE deletion (so we can track WHO/WHEN/WHY/WHAT)
    await logAudit(ctx, {
      userId: operationArgs.deletedBy,
      action: AuditActions.DELETE_STUDENT,
      targetType: AuditTargetTypes.STUDENTS,
      targetId: operationArgs.id,
      targetName: `${student.firstName} ${student.lastName}`,
      reason: operationArgs.reason,
      schoolId: student.schoolId,
      details: {
        studentId: student.studentId,
        grade: student.grade,
        class: student.class,
        guardianId: student.guardianId,
        area: student.area,
        affectedClasses: activeClasses.length,
        affectedClassIds: activeClasses.map(c => c._id),
      },
    });

    await ctx.db.delete(operationArgs.id);

    return { success: true };
  },
});

// Mutation to duplicate a student (for guardian-linked students)
export const duplicate = mutation({
  args: {
    id: v.id("students"),
  },
  handler: async (ctx, args) => {
    const originalStudent = await ctx.db.get(args.id);

    if (!originalStudent) {
      throw new Error("Student not found");
    }

    // Only allow duplication for guardian-linked students
    if (originalStudent.schoolId) {
      throw new Error("Can only duplicate guardian-linked students");
    }

    // Generate new unique student ID
    const schoolIdForHash = "GUARDIAN";
    let studentId = generateStudentId(originalStudent.firstName, originalStudent.lastName, schoolIdForHash);

    let attempts = 0;
    const maxAttempts = 10;

    while (attempts < maxAttempts) {
      const existing = await ctx.db
        .query("students")
        .withIndex("by_student_id", (q) => q.eq("studentId", studentId))
        .first();

      if (!existing) {
        break;
      }

      studentId = generateStudentId(originalStudent.firstName, originalStudent.lastName, schoolIdForHash);
      attempts++;
    }

    if (attempts === maxAttempts) {
      throw new Error("Failed to generate unique student ID after multiple attempts");
    }

    // Create duplicate with new ID
    const newId = await ctx.db.insert("students", {
      firstName: originalStudent.firstName,
      lastName: originalStudent.lastName,
      studentId,
      schoolId: originalStudent.schoolId,
      guardianId: originalStudent.guardianId,
      guardianTitle: originalStudent.guardianTitle,
      grade: originalStudent.grade,
      guardianName: originalStudent.guardianName,
      guardianPhone: originalStudent.guardianPhone,
      guardianEmail: originalStudent.guardianEmail,
      acknowledged: originalStudent.acknowledged,
      createdBy: originalStudent.createdBy,
      createdAt: Date.now(),
    });

    return { id: newId, studentId };
  },
});

// Query to get students created by a specific teacher
export const getByTeacher = query({
  args: {
    teacherId: v.id("users"),
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("students")
      .withIndex("by_created_by", (q) => q.eq("createdBy", args.teacherId))
      .collect();
  },
});

// Query to get students for a guardian
export const getByGuardianId = query({
  args: {
    guardianId: v.id("users"),
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("students")
      .withIndex("by_guardian_id", (q) => q.eq("guardianId", args.guardianId))
      .collect();
  },
});

// Mutation for guardian to acknowledge a student
export const acknowledgeStudent = mutation({
  args: {
    studentId: v.id("students"),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.studentId, {
      acknowledged: true,
    });

    return { success: true };
  },
});

// Migration mutation to auto-classify existing students with "K" pattern
export const migrateClassField = mutation({
  args: {},
  handler: async (ctx) => {
    const allStudents = await ctx.db.query("students").collect();
    let updatedCount = 0;

    for (const student of allStudents) {
      // Skip if class is already set or student is not linked to a school
      if (student.class || !student.schoolId) {
        continue;
      }

      // Check grade, firstName, lastName, nickname, and notes for K1, K2, or K3
      const nickname = "nickname" in student ? student.nickname : "";
      const notes = "notes" in student ? student.notes : "";
      const searchFields = [
        student.grade,
        student.firstName,
        student.lastName,
        nickname || "",
        notes || "",
      ].join(" ").toUpperCase();

      let detectedClass: string | null = null;

      // Check for K1, K2, K3 patterns
      if (/\bK1\b/.test(searchFields) || /\bK\s*1\b/.test(searchFields)) {
        detectedClass = "K1";
      } else if (/\bK2\b/.test(searchFields) || /\bK\s*2\b/.test(searchFields)) {
        detectedClass = "K2";
      } else if (/\bK3\b/.test(searchFields) || /\bK\s*3\b/.test(searchFields)) {
        detectedClass = "K3";
      }

      // Update student if class was detected
      if (detectedClass) {
        await ctx.db.patch(student._id, { class: detectedClass });
        updatedCount++;
      }
    }

    return {
      success: true,
      message: `Successfully updated ${updatedCount} student(s) with detected class`,
      updatedCount
    };
  },
});
