#!/usr/bin/env node
/**
 * Generate Convex Hooks from API Schema
 *
 * This script reads the Convex API schema and generates typed React hooks
 * for use with TanStack Query. Run with: `npx tsx scripts/generate-hooks.ts`
 */

import { writeFileSync, mkdirSync } from "fs";
import { resolve } from "path";

const HOOKS_TEMPLATE = `// Generated Convex Hooks with TanStack Query integration
// Auto-generated by scripts/generate-hooks.ts - DO NOT EDIT MANUALLY
// Run \`npm run generate:hooks\` to regenerate

import { useQuery, useMutation } from "@tanstack/react-query";
import { useQuery as useConvexQuery, useMutation as useConvexMutation } from "convex/react";
import { api } from "../../_generated/api";
import { Id } from "../../_generated/dataModel";

// ============================================
// Students Hooks
// ============================================

export function useStudents(filters?: {
  providerId?: Id<"providers">;
  schoolId?: Id<"schools">;
  grade?: string;
  includeDeleted?: boolean;
}) {
  return useQuery({
    queryKey: ["students", filters],
    queryFn: () => useConvexQuery(api.students.list, filters),
    enabled: true,
  });
}

export function useStudent(id: Id<"students">) {
  return useQuery({
    queryKey: ["student", id],
    queryFn: () => useConvexQuery(api.students.get, { id }),
    enabled: !!id,
  });
}

export function useCreateStudent() {
  return useConvexMutation(api.students.create);
}

export function useUpdateStudent() {
  return useConvexMutation(api.students.update);
}

export function useDeleteStudent() {
  return useConvexMutation(api.students.delete);
}

// ============================================
// Classes Hooks
// ============================================

export function useClasses(filters?: {
  providerId?: Id<"providers">;
  schoolId?: Id<"schools">;
  teacherId?: Id<"users">;
  status?: "pending" | "approved" | "rejected" | "completed";
  startDate?: number;
  endDate?: number;
}) {
  return useQuery({
    queryKey: ["classes", filters],
    queryFn: () => useConvexQuery(api.classes.list, filters),
    enabled: true,
  });
}

export function useClass(id: Id<"classes">) {
  return useQuery({
    queryKey: ["class", id],
    queryFn: () => useConvexQuery(api.classes.get, { id }),
    enabled: !!id,
  });
}

export function useCreateClass() {
  return useConvexMutation(api.classes.create);
}

export function useUpdateClass() {
  return useConvexMutation(api.classes.update);
}

export function useDeleteClass() {
  return useConvexMutation(api.classes.delete);
}

export function useApproveClass() {
  return useConvexMutation(api.classes.approve);
}

export function useRejectClass() {
  return useConvexMutation(api.classes.reject);
}

// ============================================
// Providers Hooks
// ============================================

export function useProviders(filters?: {
  category?: "personal" | "private" | "language_school" | "educational_camp";
  isActive?: boolean;
  createdBy?: Id<"users">;
}) {
  return useQuery({
    queryKey: ["providers", filters],
    queryFn: () => useConvexQuery(api.providers.list, filters),
    enabled: true,
  });
}

export function useProvider(id: Id<"providers">) {
  return useQuery({
    queryKey: ["provider", id],
    queryFn: () => useConvexQuery(api.providers.get, { id }),
    enabled: !!id,
  });
}

export function useCreateProvider() {
  return useConvexMutation(api.providers.create);
}

export function useUpdateProvider() {
  return useConvexMutation(api.providers.update);
}

export function useDeleteProvider() {
  return useConvexMutation(api.providers.delete);
}

// ============================================
// Schools Hooks
// ============================================

export function useSchools(filters?: {
  moderatorId?: Id<"users">;
  province?: string;
}) {
  return useQuery({
    queryKey: ["schools", filters],
    queryFn: () => useConvexQuery(api.schools.list, filters),
    enabled: true,
  });
}

export function useSchool(id: Id<"schools">) {
  return useQuery({
    queryKey: ["school", id],
    queryFn: () => useConvexQuery(api.schools.get, { id }),
    enabled: !!id,
  });
}

export function useCreateSchool() {
  return useConvexMutation(api.schools.create);
}

export function useUpdateSchool() {
  return useConvexMutation(api.schools.update);
}

// ============================================
// Locations Hooks
// ============================================

export function useLocations(filters?: {
  type?: "school" | "private";
  providerId?: Id<"providers">;
}) {
  return useQuery({
    queryKey: ["locations", filters],
    queryFn: () => useConvexQuery(api.locations.list, filters),
    enabled: true,
  });
}

export function useLocation(id: Id<"locations">) {
  return useQuery({
    queryKey: ["location", id],
    queryFn: () => useConvexQuery(api.locations.get, { id }),
    enabled: !!id,
  });
}

export function useCreateLocation() {
  return useConvexMutation(api.locations.create);
}

export function useUpdateLocation() {
  return useConvexMutation(api.locations.update);
}

// ============================================
// Users Hooks
// ============================================

export function useCurrentUser() {
  return useQuery({
    queryKey: ["currentUser"],
    queryFn: () => useConvexQuery(api.users.getCurrentUser),
  });
}

export function useUser(id: Id<"users">) {
  return useQuery({
    queryKey: ["user", id],
    queryFn: () => useConvexQuery(api.users.get, { id }),
    enabled: !!id,
  });
}

export function useUsers(filters?: {
  role?: "teacher" | "moderator" | "admin";
  schoolId?: Id<"schools">;
}) {
  return useQuery({
    queryKey: ["users", filters],
    queryFn: () => useConvexQuery(api.users.list, filters),
    enabled: true,
  });
}

export function useUpdateProfile() {
  return useConvexMutation(api.users.updateProfile);
}

// ============================================
// Analytics Hooks
// ============================================

export function useClassStats(filters?: {
  providerId?: Id<"providers">;
  schoolId?: Id<"schools">;
  teacherId?: Id<"users">;
  startDate?: number;
  endDate?: number;
}) {
  return useQuery({
    queryKey: ["classStats", filters],
    queryFn: () => useConvexQuery(api.analytics.classStats, filters),
    enabled: true,
  });
}

export function useProviderStats(providerId: Id<"providers">) {
  return useQuery({
    queryKey: ["providerStats", providerId],
    queryFn: () => useConvexQuery(api.analytics.providerStats, { providerId }),
    enabled: !!providerId,
  });
}

export function useTeacherStats(teacherId: Id<"users">) {
  return useQuery({
    queryKey: ["teacherStats", teacherId],
    queryFn: () => useConvexQuery(api.analytics.teacherStats, { teacherId }),
    enabled: !!teacherId,
  });
}

// ============================================
// Notifications Hooks
// ============================================

export function useNotifications(filters?: {
  userId?: Id<"users">;
  isRead?: boolean;
  limit?: number;
}) {
  return useQuery({
    queryKey: ["notifications", filters],
    queryFn: () => useConvexQuery(api.notifications.list, filters),
    enabled: true,
  });
}

export function useUnreadNotificationCount(userId: Id<"users">) {
  return useQuery({
    queryKey: ["unreadNotifications", userId],
    queryFn: () => useConvexQuery(api.notifications.getUnreadCount, { userId }),
    enabled: !!userId,
  });
}

export function useMarkNotificationRead() {
  return useConvexMutation(api.notifications.markAsRead);
}

export function useMarkAllNotificationsRead() {
  return useConvexMutation(api.notifications.markAllAsRead);
}
`;

function main() {
  const outputPath = resolve("lib/convex/hooks.ts");

  try {
    writeFileSync(outputPath, HOOKS_TEMPLATE);
    console.log(`✅ Generated hooks at ${outputPath}`);
  } catch (error) {
    console.error("❌ Failed to generate hooks:", error);
    process.exit(1);
  }
}

main();
