import { Doc } from "../../convex/_generated/dataModel";

let idCounter = 0;
const generateId = (prefix: string) => `${prefix}_${Date.now()}_${++idCounter}`;

type User = Doc<"users">;
type School = Doc<"schools">;
type Provider = Doc<"providers">;
type Student = Doc<"students">;

export interface TestUserInput {
  username?: string;
  password?: string;
  role?: User["role"];
  schoolId?: User["schoolId"];
  requirePasswordChange?: boolean;
  preferredLanguage?: User["preferredLanguage"];
}

export interface TestSchoolInput {
  name?: string;
  nameTh?: string;
  moderatorId?: School["moderatorId"];
  district?: School["district"];
  province?: School["province"];
}

export interface TestProviderInput {
  name?: string;
  nameTh?: string;
  category?: Provider["category"];
  createdBy: Provider["createdBy"];
  isActive?: boolean;
  isAutoGenerated?: boolean;
}

export interface TestStudentInput {
  firstName?: string;
  lastName?: string;
  studentId?: string;
  schoolId?: Student["schoolId"];
  providerId?: Student["providerId"];
  grade?: string;
  class?: string;
  guardianName?: string;
  guardianPhone?: string;
  guardianEmail?: string;
  nickname?: string;
  dateOfBirth?: number;
  provinceCode?: string;
  districtName?: string;
  parentName?: string;
  parentPhone?: string;
  parentEmail?: string;
  createdBy?: Student["createdBy"];
}

const defaultPasswordHash = "pbkdf2$test$salt$hash";

export const createTestUser = (
  input: TestUserInput = {},
): Omit<User, "_id" | "_creationTime"> => {
  const username = input.username || `user_${generateId("u")}`;
  return {
    username,
    passwordHash: input.password
      ? `pbkdf2$test$${generateId("pw")}`
      : defaultPasswordHash,
    role: input.role || "teacher",
    schoolId: input.schoolId,
    requirePasswordChange: input.requirePasswordChange ?? false,
    createdAt: Date.now(),
    preferredLanguage: input.preferredLanguage || "en",
  };
};

export const createTestSchool = (
  input: TestSchoolInput = {},
): Omit<School, "_id" | "_creationTime"> => {
  const name = input.name || `School ${generateId("sch")}`;
  return {
    name,
    nameTh: input.nameTh || `โรงเรียน${name}`,
    moderatorId: input.moderatorId,
    createdAt: Date.now(),
    district: input.district,
    districtTh: input.district ? `เขต${input.district}` : undefined,
    province: input.province,
    provinceTh: input.province ? `จังหวัด${input.province}` : undefined,
  };
};

export const createTestProvider = (
  input: TestProviderInput,
): Omit<Provider, "_id" | "_creationTime"> => {
  const name = input.name || `Provider ${generateId("prov")}`;
  return {
    name,
    nameTh: input.nameTh || `ผู้ให้บริการ${name}`,
    category: input.category || "personal",
    createdBy: input.createdBy,
    isActive: input.isActive ?? true,
    createdAt: Date.now(),
    isAutoGenerated: input.isAutoGenerated ?? false,
  };
};

export const createTestStudent = (
  input: TestStudentInput = {},
): Omit<Student, "_id" | "_creationTime"> => {
  const firstName = input.firstName || `First${generateId("fn")}`;
  const lastName = input.lastName || `Last${generateId("ln")}`;
  return {
    firstName,
    lastName,
    studentId: input.studentId || `STU-${generateId("stu")}`,
    schoolId: input.schoolId,
    providerId: input.providerId,
    guardianId: undefined,
    guardianTitle: "Parent",
    grade: input.grade || "K1",
    class: input.class || "/1",
    guardianName: input.guardianName || `Parent of ${firstName}`,
    guardianPhone: input.guardianPhone || "080-000-0000",
    guardianEmail: input.guardianEmail || `parent@${generateId("email")}.com`,
    acknowledged: false,
    createdBy: input.createdBy,
    createdAt: Date.now(),
    nickname: input.nickname || firstName,
    dateOfBirth: input.dateOfBirth || new Date("2015-01-01").getTime(),
    area: undefined,
    provinceCode: input.provinceCode,
    districtName: input.districtName,
    parentName: input.parentName,
    parentPhone: input.parentPhone,
    parentEmail: input.parentEmail,
    secondaryParentName: undefined,
    secondaryParentPhone: undefined,
    allergies: undefined,
    specialNeeds: undefined,
    medicalNotes: undefined,
    notes: undefined,
    isDeleted: false,
    deletedAt: undefined,
    deletedBy: undefined,
    deletionReason: undefined,
  };
};

type ClassInput = {
  teacherId: string;
  studentId: string;
  schoolId?: string;
  providerId?: string;
  scheduledDate?: number;
  status?: "pending" | "acknowledged" | "approved" | "rejected";
  duration?: number;
  subject?: string;
} & Record<string, unknown>;

const CLASS_OVERRIDE_KEYS = [
  "_id",
  "_creationTime",
  "teacherId",
  "studentId",
  "schoolId",
  "providerId",
  "scheduledDate",
  "status",
  "duration",
  "subject",
  "subjectTh",
  "classType",
  "createdAt",
  "bookedByUserId",
  "additionalStudentIds",
  "locationId",
  "pendingLocationName",
  "pendingLocationNameTh",
  "guardianTitle",
  "isGuardianLinked",
  "lessonTopic",
  "lessonTopicTh",
  "materials",
  "materialsTh",
  "preparationNotes",
  "preparationNotesTh",
  "isEdited",
  "lastEditedAt",
  "lastEditedBy",
  "editHistory",
  "bookedByUsername",
  "approvedByUserId",
  "approvedByUsername",
  "approvedAt",
  "approvalSource",
  "flaggedForReview",
  "includeInReports",
  "reviewNotes",
  "reviewNotesTh",
  "flaggedBy",
  "flaggedAt",
  "loggedAt",
  "actualDuration",
  "attendance",
  "deletedAt",
] as const satisfies readonly string[];

export const createTestClass = (input: ClassInput) => {
  const { subject: _subject, ...rest } = input;
  const overrideKeys: string[] = CLASS_OVERRIDE_KEYS as unknown as string[];
  const extra = Object.fromEntries(
    Object.entries(rest).filter(([key]) => !overrideKeys.includes(key)),
  );
  return {
    teacherId: input.teacherId,
    studentId: input.studentId,
    schoolId: input.schoolId,
    providerId: input.providerId,
    scheduledDate: input.scheduledDate || Date.now(),
    status: input.status || "pending",
    duration: input.duration || 60,
    subject: input.subject,
    subjectTh: input.subject ? `วิชา${input.subject}` : undefined,
    classType: "regular" as const,
    createdAt: Date.now(),
    bookedByUserId: input.teacherId,
    ...extra,
  };
};

export const createTestNotification = (
  input: {
    userId?: string;
    type?: "info" | "success" | "warning" | "error";
    message?: string;
  } = {},
) => {
  return {
    title: input.message || "Test Notification",
    titleTh: "การแจ้งเตือนทดสอบ",
    message: input.message || "This is a test notification",
    messageTh: "นี่คือการแจจ้งเตือนทดสอบ",
    type: input.type || "info",
    userId: input.userId,
    read: false,
    createdAt: Date.now(),
  };
};
